//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class DMR_ZoneForm {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal DMR_ZoneForm() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMR.ZoneForm", typeof(DMR_ZoneForm).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnAdd_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnAdd.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnDel_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnDel.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnFirst_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnFirst.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnLast_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnLast.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnNext_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnNext.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnPrev_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnPrev.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
