//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class DMR_aR3nbf8dQp2feLmk31_lSfgApatkdxsVcGcrktoFd {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal DMR_aR3nbf8dQp2feLmk31_lSfgApatkdxsVcGcrktoFd() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMR.aR3nbf8dQp2feLmk31.lSfgApatkdxsVcGcrktoFd", typeof(DMR_aR3nbf8dQp2feLmk31_lSfgApatkdxsVcGcrktoFd).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Boolean, аналогичного False.
    /// </summary>
    internal static bool progressBar1_Locked {
        get {
            object obj = ResourceManager.GetObject("progressBar1.Locked", resourceCulture);
            return ((bool)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.CodeDom.MemberAttributes, аналогичного Public.
    /// </summary>
    internal static System.CodeDom.MemberAttributes progressBar1_Modifiers {
        get {
            object obj = ResourceManager.GetObject("progressBar1.Modifiers", resourceCulture);
            return ((System.CodeDom.MemberAttributes)(obj));
        }
    }
}
