//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class DMR_MainForm {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal DMR_MainForm() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMR.MainForm", typeof(DMR_MainForm).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap about {
        get {
            object obj = ResourceManager.GetObject("about", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap file {
        get {
            object obj = ResourceManager.GetObject("file", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap firmware {
        get {
            object obj = ResourceManager.GetObject("firmware", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Windows.Forms.ImageListStreamer.
    /// </summary>
    internal static System.Windows.Forms.ImageListStreamer imgMain_ImageStream {
        get {
            object obj = ResourceManager.GetObject("imgMain.ImageStream", resourceCulture);
            return ((System.Windows.Forms.ImageListStreamer)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap line_graph {
        get {
            object obj = ResourceManager.GetObject("line-graph", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap open {
        get {
            object obj = ResourceManager.GetObject("open", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap palette {
        get {
            object obj = ResourceManager.GetObject("palette", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap read {
        get {
            object obj = ResourceManager.GetObject("read", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap save {
        get {
            object obj = ResourceManager.GetObject("save", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap settings {
        get {
            object obj = ResourceManager.GetObject("settings", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap toolbox {
        get {
            object obj = ResourceManager.GetObject("toolbox", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnAbout_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnAbout.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnNew_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnNew.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnOpen_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnOpen.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnRead_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnRead.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnSave_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnSave.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap tsbtnWrite_Image {
        get {
            object obj = ResourceManager.GetObject("tsbtnWrite.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap users {
        get {
            object obj = ResourceManager.GetObject("users", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap write {
        get {
            object obj = ResourceManager.GetObject("write", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
